from escpos.printer import Usb

SEP = '********************************'
p = Usb(0x0416, 0x5011, profile="TM-T88II")

p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='center', bold=True)
p.text("COCINA LALITA\n")
p.set(align='center', bold=False)
p.text("MUYUGUARDA 15 SAN BERNARDINO\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='center', bold=True)
p.text("¡GRACIAS POR SU VISITA!\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='left', bold=False)
p.text("ORDEN DE MESA\n")
p.set(align='left', bold=False)
p.text("FOLIO: 0          FECHA: 13/05/2026\n")
p.set(align='left', bold=False)
p.text("MESA:  1          HORA: 11:45 AM\n")
p.set(align='left', bold=False)
p.text("PERSONAS: 2      ORDEN: PARA COMER\n")
p.set(align='left', bold=False)
p.text("MESERO: MARGARITA\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='left', bold=True)
p.text("CANT  DESCRIPCION    IMPORTE\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='left', bold=False)
p.text("2     COMIDA CORRIDA $210.00\n")
p.set(align='left', bold=False)
p.text("3     REFRESCOS      $90.00\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='left', bold=False)
p.text("TOTAL ARTICULOS: 5\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='left', bold=False)
p.text("SUBTOTAL:      $300.00\n")
p.set(align='left', bold=False)
p.text("IVA (16%):     0\n")
p.set(align='left', bold=True)
p.text("TOTAL:         $300.00\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='left', bold=False)
p.text("FORMA DE PAGO: EFECTIVO\n")
p.set(align='left', bold=False)
p.text("MONTO RECIBIDO: $300.00\n")
p.set(align='left', bold=False)
p.text("CAMBIO:         $0.00\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='center', bold=True)
p.text("¡GRACIAS POR SU VISITA!\n")
p.set(align='center', bold=False)
p.text("LOS ESPERAMOS PRONTO\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='left', bold=False)
p.text("TERMINAL:        0\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.set(align='center', bold=True)
p.text("¡FACTURA SOLICITALA AL\n")
p.set(align='center', bold=True)
p.text("MOMENTO DEL PAGO!\n")
p.set(align='left', bold=False)
p.text(SEP + "\n")
p.ln(3)
p.cut()
